export const dataStatuses = [
  { _id: "active", title: "Active", status: "Active" },
  { _id: "inactive", title: "Inactive", status: "Inactive" },
];
export const rolesData = [
  { _id: "admin", title: "Admin" },
  { _id: "branch", title: "Branch" },
  { _id: "report", title: "Report" },
  { _id: "seller", title: "Seller" },
  { _id: "stock", title: "Stock" },
  { _id: "auditReport", title: "Audit Report" },
  { _id: "user", title: "User" },
];
export const dataProvince = [
  { _id: "ratanakiri", title: "រតនគីរី" },
  { _id: "mondulkiri", title: "មណ្ឌលគិរី" },
  { _id: "stungtreng", title: "ស្ទឹងត្រែង" },
  { _id: "banteaymeanchey", title: "បន្ទាយមានជ័យ" },
  { _id: "battambang", title: "បាត់ដំបង" },
  { _id: "siemreap", title: "សៀមរាប" },
  { _id: "kampongcham", title: "កំពង់ចាម" },
  { _id: "kampongchhnang", title: "កំពង់ឆ្នាំង" },
  { _id: "kampongthom", title: "កំពង់ធំ" },
  { _id: "kampongspeu", title: "កំពង់ស្ពឺ" },
  { _id: "kampot", title: "កំពត" },
  { _id: "kandal", title: "កណ្តាល" },
  { _id: "kep", title: "កែប" },
  { _id: "kohkong", title: "កោះកុង" },
  { _id: "kratié", title: "ក្រចេះ" },
  { _id: "tboungkhmum", title: "ត្បូងឃ្មុំ" },
  { _id: "oddarmeanchey", title: "ឧត្តរមានជ័យ" },
  { _id: "preahvihear", title: "ព្រះវិហារ" },
  { _id: "pursat", title: "ពោធិ៍សាត់" },
  { _id: "Pailin", title: "ប៉ៃលិន" },
  { _id: "preahsihanouk", title: "ព្រះសីហនុ" },
  { _id: "preyveng", title: "ព្រៃវែង" },
  { _id: "svayrieng", title: "ស្វាយរៀង" },
  { _id: "takéo", title: "តាកែវ" },
];
