version: '3.9'

services:
  nextapp:
    container_name: ecmapp
    image: ecmapp
    restart: unless-stopped
    #env_file: .env
    build: .
    ports:
      - "3000:3000"
    # environment:
    #   - AUTH_SECRET=$AUTH_SECRET
    #   - AUTH_GITHUB_ID=$AUTH_GITHUB_ID
    #   - AUTH_GITHUB_SECRET=$AUTH_GITHUB_SECRET
    #   - AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID
    #   - AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET
    #   - MONGODB_URI=$MONGODB_URI
    #   - SETTING_ID=$SETTING_ID


